#pragma once

enum class TokenType
{
    OPENING_ROUND_BRACKET,
    CLOSING_ROUND_BRACKET,
    OPENING_SQUARE_BRACKET,
    CLOSING_SQUARE_BRACKET,
    FUNCTION_NAME,
    ARROW,
    COMMA,
    ARGUMENT,
    WHOLE_NUMBER,
    FRACTIONAL_NUMBER,
};